#version: '3.8'

services:
  haproxy:
    image: haproxy:2.9
    container_name: haproxy-mtls-proxy
    network_mode: host
    ports:
      - "20000:20000"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certs:/usr/local/etc/haproxy/certs:ro
